//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Driver.Dal.Invitation.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociatedGroupWall
    {
        public long Id { get; set; }
        public Nullable<long> IdUsers { get; set; }
        public Nullable<long> IdAssociatedGroups { get; set; }
        public string Post { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual AssociatedGroups AssociatedGroups { get; set; }
        public virtual Users Users { get; set; }
    }
}
