//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Driver.Dal.Invitation.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.CarsPictures = new HashSet<CarsPictures>();
            this.CarsUsers = new HashSet<CarsUsers>();
            this.TravelToWork = new HashSet<TravelToWork>();
        }
    
        public long Id { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<long> IdCarTypeDictionary { get; set; }
        public Nullable<long> IdColour { get; set; }
        public Nullable<int> Seats { get; set; }
    
        public virtual CarTypeDictionary CarTypeDictionary { get; set; }
        public virtual Colours Colours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsPictures> CarsPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsUsers> CarsUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelToWork> TravelToWork { get; set; }
    }
}
