//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Driver.Dal.Invitation.Interfaces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriverEntities : DbContext
    {
        public DriverEntities()
            : base("name=DriverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarDictionary> CarDictionary { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<CarsPictures> CarsPictures { get; set; }
        public virtual DbSet<CarsUsers> CarsUsers { get; set; }
        public virtual DbSet<CarTypeDictionary> CarTypeDictionary { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Colours> Colours { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<GroupUsers> GroupUsers { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Phrases> Phrases { get; set; }
        public virtual DbSet<Translations> Translations { get; set; }
        public virtual DbSet<TravelToWork> TravelToWork { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersLocations> UsersLocations { get; set; }
        public virtual DbSet<UsersReferences> UsersReferences { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
        public virtual DbSet<WorkTrip> WorkTrip { get; set; }
        public virtual DbSet<AssociatedGroups> AssociatedGroups { get; set; }
        public virtual DbSet<AssociatedGroupUsers> AssociatedGroupUsers { get; set; }
        public virtual DbSet<AssociatedGroupWall> AssociatedGroupWall { get; set; }
    }
}
