//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Driver.Dal.Invitation.Interfaces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriverEntities1 : DbContext
    {
        public DriverEntities1()
            : base("name=DriverEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarDictionary> CarDictionaries { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarsUser> CarsUsers { get; set; }
        public virtual DbSet<CarTypeDictionary> CarTypeDictionaries { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Colour> Colours { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<WorkTrip> WorkTrips { get; set; }
    }
}
