//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.Driver.Dal.Invitation.Interfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersLocations
    {
        public long Id { get; set; }
        public Nullable<long> IdUsers { get; set; }
        public Nullable<long> IdCity { get; set; }
        public string Street { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<int> Kind { get; set; }
    
        public virtual City City { get; set; }
        public virtual Users Users { get; set; }
    }
}
